pipeline:
  identifier: Build_hashinyc_grafana_1746729656658
  name: Build grafana
  orgIdentifier: default
  projectIdentifier: CI_Pipeline
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1746652796717
        repoName: hashinyc/grafana
  stages:
    - stage:
        name: Docker Build
        identifier: Docker_Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.DockerHub
                    repo: baiyun/grafana
                    tags:
                      - latest
                    caching: false
